# Generated by Django 2.2.1 on 2020-02-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.TextField(verbose_name='メッセージ')),
                ('read', models.CharField(max_length=100, verbose_name='既読')),
                ('created_at', models.DateField(verbose_name='日時')),
            ],
        ),
    ]
