# Generated by Django 2.2.1 on 2020-02-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_talktype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talktype',
            options={'verbose_name_plural': 'カテゴリー'},
        ),
    ]
