# Generated by Django 2.2.1 on 2020-02-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_auto_20200203_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkmodel',
            name='talk_type',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, to='talk.TalkType', verbose_name='カテゴリー'),
            preserve_default='True',
        ),
    ]
