# Generated by Django 2.2.1 on 2020-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0004_talkmodel_talk_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talkmodel',
            options={'verbose_name_plural': 'トーク'},
        ),
        migrations.AddField(
            model_name='talkmodel',
            name='image',
            field=models.ImageField(null='True', upload_to='images/', verbose_name='画像'),
            preserve_default='True',
        ),
    ]
