# Generated by Django 2.2.1 on 2020-02-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0006_talkmodel_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alubum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null='True', upload_to='images/', verbose_name='画像')),
            ],
        ),
        migrations.RemoveField(
            model_name='talkmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='talkmodel',
            name='image_id',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, to='talk.Alubum', verbose_name='画像複数'),
            preserve_default='True',
        ),
    ]
