# Generated by Django 2.2.1 on 2020-02-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0007_auto_20200203_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alubum',
            options={'verbose_name_plural': 'イメージ'},
        ),
        migrations.RemoveField(
            model_name='talkmodel',
            name='image_id',
        ),
        migrations.AddField(
            model_name='alubum',
            name='talk_id',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.PROTECT, to='talk.TalkModel', verbose_name='トークID'),
            preserve_default='False',
        ),
    ]
