# Generated by Django 2.2.1 on 2020-02-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0008_auto_20200203_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alubum',
            name='image',
            field=models.ImageField(null='True', upload_to='', verbose_name='画像'),
        ),
    ]
